# Generated by Django 4.0.3 on 2023-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vip_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
