# Generated by Django 4.0.3 on 2023-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_color',
            field=models.CharField(default='green', max_length=200, null=True),
        ),
    ]
